import { db } from './firebase.js';
import {
    collection, doc, getDocs, onSnapshot, serverTimestamp, addDoc, deleteDoc, updateDoc
} from "https://www.gstatic.com/firebasejs/12.10.0/firebase-firestore.js";
import { normalizeClasses } from './categories.js';

// ─────────────────────────────────────────────
// Module State
// ─────────────────────────────────────────────
let allPrograms = [];
let allCategories = [];
let allTeams = [];
let allResults = [];
let unsubscribeExports = null;
let exportsList = [];

// ─────────────────────────────────────────────
// Init View
// ─────────────────────────────────────────────
export async function initExportsView(container, topActions) {
    if (!window.currentInstituteId) {
        container.innerHTML = '<div class="empty-state"><h3>Access Denied</h3><p>Please log in again.</p></div>';
        return;
    }

    if (unsubscribeExports) {
        unsubscribeExports();
        unsubscribeExports = null;
    }

    allPrograms = [];
    allCategories = [];
    allTeams = [];
    allResults = [];
    exportsList = [];

    // Inject New Export Action Button in Topbar with standard ID newExportBtn
    topActions.innerHTML = `
        <button class="btn btn-primary" id="newExportBtn" style="font-weight:700;">
            📥 + New Export
        </button>
    `;

    // Render Scaffolding
    container.innerHTML = `
        <div style="display:flex; flex-direction:column; gap:1.5rem; width:100%;">
            <!-- Subtitle Info -->
            <div style="background:#f8fafc; border:1px solid #cbd5e1; border-radius:12px; padding:1rem 1.25rem; display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:1rem;">
                <div>
                    <h3 style="margin:0; font-size:1.1rem; font-weight:800; color:#1e1b4b;">📤 Event Exports Center</h3>
                    <p style="margin:0.2rem 0 0 0; font-size:0.8rem; color:#64748b; font-weight:600;">Generate and download event documents, blank markings, call lists, and results.</p>
                </div>
            </div>

            <!-- History Logs Table -->
            <div class="card" style="padding:1.25rem; border-color:#cbd5e1; width:100%; box-shadow:0 1px 3px rgba(0,0,0,0.05);">
                <h3 style="font-size:1rem; font-weight:800; color:#0f172a; margin-top:0; margin-bottom:1rem; display:flex; align-items:center; gap:0.4rem;">
                    📜 Export History Logs
                </h3>
                <div style="overflow-x:auto; background:#fff; border:1px solid #e2e8f0; border-radius:10px; width:100%;">
                    <table style="width:100%; border-collapse:collapse; min-width:800px; font-size:0.85rem; color:#1e293b;">
                        <thead>
                            <tr style="background:#f8fafc; border-bottom:2px solid #cbd5e1; text-align:left;">
                                <th style="padding:0.75rem 1rem; color:#475569; font-weight:700;">Export Type</th>
                                <th style="padding:0.75rem 1rem; color:#475569; font-weight:700;">File Name</th>
                                <th style="padding:0.75rem 1rem; color:#475569; font-weight:700; width:160px;">Created Date</th>
                                <th style="padding:0.75rem 1rem; color:#475569; font-weight:700; width:140px; text-align:center;">Generated By</th>
                                <th style="padding:0.75rem 1rem; color:#475569; font-weight:700; width:140px; text-align:center;">Status</th>
                                <th style="padding:0.75rem 1rem; color:#475569; font-weight:700; width:220px; text-align:center;">Actions</th>
                            </tr>
                        </thead>
                        <tbody id="exportHistoryBody">
                            <tr><td colspan="6" style="text-align:center; padding:2rem; color:#64748b;">Loading history...</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    `;

    // Attach click listener after DOM rendering
    const newExportBtn = document.getElementById("newExportBtn");
    if (newExportBtn) {
        newExportBtn.addEventListener("click", () => {
            console.log("New Export clicked");
            openExportDrawer();
        });
    }

    await loadStaticData();
    subscribeExportsHistory();

    console.log("Exports initialized");
}

// ─────────────────────────────────────────────
// Data Listeners & Static Loads
// ─────────────────────────────────────────────
async function loadStaticData() {
    try {
        const instId = window.currentInstituteId;

        // Categories
        const catSnap = await getDocs(collection(db, "institutes", instId, "categories"));
        allCategories = catSnap.docs.map(d => ({ id: d.id, ...d.data(), classes: normalizeClasses(d.data().classes) }));

        // Programs
        const progSnap = await getDocs(collection(db, "institutes", instId, "programs"));
        allPrograms = progSnap.docs.map(progDoc => {
            const p = progDoc.data();
            const pType = (p.programType || p.type || 'individual').toLowerCase();
            return {
                id: progDoc.id,
                programName: p.programName || 'Unnamed Program',
                programType: pType,
                type: pType === 'group' ? 'Group' : 'Individual',
                genderCategory: p.genderCategory || 'Mixed',
                programLocation: p.programLocation || 'Stage',
                categoryId: p.categoryId || '',
                categoryName: p.categoryName || p.categoryId || 'General',
                classId: p.classId || '',
                className: p.className || ''
            };
        });

        // Teams
        const teamSnap = await getDocs(collection(db, "institutes", instId, "teams"));
        allTeams = teamSnap.docs.map(d => ({ id: d.id, name: d.data().name }));

    } catch (e) {
        console.error("Failed loading static data for Exports:", e);
    }
}

function subscribeExportsHistory() {
    const instId = window.currentInstituteId;
    const ref = collection(db, "institutes", instId, "exports");

    unsubscribeExports = onSnapshot(ref, (snapshot) => {
        exportsList = snapshot.docs.map(docSnap => ({ id: docSnap.id, ...docSnap.data() }));
        
        // Sort history by queuedAt descending (most recent first)
        exportsList.sort((a, b) => {
            const tA = a.queuedAt?.seconds || 0;
            const tB = b.queuedAt?.seconds || 0;
            return tB - tA;
        });

        renderHistoryLogs();
    });
}

function renderHistoryLogs() {
    const tbody = document.getElementById('exportHistoryBody');
    if (!tbody) return;

    if (exportsList.length === 0) {
        tbody.innerHTML = `<tr><td colspan="6" style="text-align:center; padding:2rem; color:#64748b;">No exports generated yet. Click <strong>📥 + New Export</strong> to start.</td></tr>`;
        return;
    }

    tbody.innerHTML = exportsList.map(exp => {
        let statusBadge = '';
        if (exp.status === 'Pending') {
            statusBadge = '<span class="badge" style="background:#f1f5f9; color:#475569; border:1px solid #cbd5e1;">⌛ Pending</span>';
        } else if (exp.status === 'Processing') {
            statusBadge = '<span class="badge" style="background:#eff6ff; color:#1d4ed8; border:1px solid #93c5fd;">⚙️ Processing</span>';
        } else if (exp.status === 'Completed') {
            statusBadge = '<span class="badge" style="background:#f0fdf4; color:#15803d; border:1px solid #bbf7d0;">✅ Completed</span>';
        } else if (exp.status === 'Failed') {
            statusBadge = '<span class="badge" style="background:#fef2f2; color:#dc2626; border:1px solid #fecaca;">❌ Failed</span>';
        } else if (exp.status === 'Cancelled') {
            statusBadge = '<span class="badge" style="background:#fff7ed; color:#ea580c; border:1px solid #ffedd5;">🚫 Cancelled</span>';
        }

        const dateStr = exp.queuedAt ? new Date(exp.queuedAt.seconds * 1000).toLocaleString() : '—';
        const generatedBy = exp.generatedBy || 'Admin';
        const summaryText = exp.fileName || '—';

        // Action Buttons states
        const canDownload = exp.status === 'Completed';
        const canRetry = exp.status === 'Failed';

        return `
            <tr style="border-bottom:1px solid #e2e8f0; hover:background:#f8fafc;">
                <td style="padding:0.75rem 1rem; font-weight:700; color:#1e1b4b;">📄 ${window.escapeHTML(exp.type)}</td>
                <td style="padding:0.75rem 1rem; color:#475569; font-weight:600; max-width:240px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">
                    ${window.escapeHTML(summaryText)}
                </td>
                <td style="padding:0.75rem 1rem; color:#64748b;">${dateStr}</td>
                <td style="padding:0.75rem 1rem; color:#475569; font-weight:600;">${window.escapeHTML(generatedBy)}</td>
                <td style="padding:0.75rem 1rem; text-align:center;">${statusBadge}</td>
                <td style="padding:0.75rem 1rem; text-align:center;">
                    <div style="display:inline-flex; gap:0.4rem; justify-content:center;">
                        <button type="button" class="btn btn-download-exp" data-id="${exp.id}" ${canDownload ? '' : 'disabled'} style="background:${canDownload ? '#f0fdf4' : '#f8fafc'}; color:${canDownload ? '#16a34a' : '#94a3b8'}; border:1px solid ${canDownload ? '#bbf7d0' : '#cbd5e1'}; font-weight:700; padding:0.3rem 0.6rem; border-radius:6px; font-size:0.78rem; cursor:${canDownload ? 'pointer' : 'not-allowed'};">
                            📥 Download
                        </button>
                        ${canRetry ? `
                        <button type="button" class="btn btn-retry-exp" data-id="${exp.id}" style="background:#eff6ff; color:#1d4ed8; border:1px solid #93c5fd; font-weight:700; padding:0.3rem 0.6rem; border-radius:6px; font-size:0.78rem; cursor:pointer;">
                            🔄 Retry
                        </button>
                        ` : ''}
                        <button type="button" class="btn btn-delete-exp" data-id="${exp.id}" style="background:#fef2f2; color:#dc2626; border:1px solid #fecaca; font-weight:700; padding:0.3rem 0.6rem; border-radius:6px; font-size:0.78rem; cursor:pointer;">
                            🗑️ Delete
                        </button>
                    </div>
                </td>
            </tr>
        `;
    }).join('');

    // Bind triggers
    tbody.querySelectorAll('.btn-download-exp').forEach(btn => {
        btn.onclick = (e) => {
            const id = btn.getAttribute('data-id');
            const exp = exportsList.find(x => x.id === id);
            if (exp) triggerDownload(exp);
        };
    });

    tbody.querySelectorAll('.btn-retry-exp').forEach(btn => {
        btn.onclick = (e) => {
            const id = btn.getAttribute('data-id');
            const exp = exportsList.find(x => x.id === id);
            if (exp) triggerRetry(exp);
        };
    });

    tbody.querySelectorAll('.btn-delete-exp').forEach(btn => {
        btn.onclick = (e) => {
            const id = btn.getAttribute('data-id');
            const exp = exportsList.find(x => x.id === id);
            if (exp) triggerDelete(exp);
        };
    });
}

// ─────────────────────────────────────────────
// Dynamic DOM Drawer Creation and Handlers
// ─────────────────────────────────────────────
function ensureExportDrawerExists() {
    try {
        let drawer = document.getElementById('exportDrawer');
        if (drawer) return drawer;

        drawer = document.createElement('div');
        drawer.id = 'exportDrawer';
        drawer.className = 'modal-overlay hidden';
        drawer.style.zIndex = '1000';

        drawer.innerHTML = `
            <div class="modal" style="width: 90%; max-width: 1100px; height: 88vh; max-height: 90vh; display: flex; flex-direction: column;">
                <div class="modal-header">
                    <h3 id="exportDrawerTitle">Create Export</h3>
                    <button class="close-modal" id="closeExportDrawerBtn">&times;</button>
                </div>
                <div class="modal-body" id="exportDrawerBody" style="padding: 1.5rem; overflow-y: auto; flex: 1;">
                    <!-- content dynamically injected -->
                </div>
            </div>
        `;
        document.body.appendChild(drawer);

        // Bind Close triggers
        document.getElementById('closeExportDrawerBtn').onclick = closeExportDrawer;

        return drawer;
    } catch (err) {
        console.error("Drawer initialization failed:", err);
        window.showToast("Unable to load export creator", "error");
        throw err;
    }
}

function openExportDrawer() {
    try {
        const drawer = ensureExportDrawerExists();
        renderDrawerContent();

        drawer.classList.remove('hidden');
        drawer.classList.add('active');
        document.body.style.overflow = 'hidden'; // lock body scroll

        console.log("Drawer opened");
    } catch (err) {
        console.error("Failed opening drawer:", err);
        window.showToast("Unable to load export creator", "error");
    }
}

function closeExportDrawer() {
    const drawer = document.getElementById('exportDrawer');
    if (drawer) {
        drawer.classList.add('hidden');
        drawer.classList.remove('active');
    }
    document.body.style.overflow = ''; // restore scroll
    console.log("Drawer closed");
}

function renderDrawerContent() {
    const body = document.getElementById('exportDrawerBody');
    if (!body) return;

    // Category options
    let catOptions = '<option value="">All Categories</option>';
    allCategories.forEach(c => {
        catOptions += `<option value="${c.id}">${window.escapeHTML(c.name)}</option>`;
    });

    // Teams options
    let teamOptions = '<option value="">All Teams</option>';
    allTeams.forEach(t => {
        teamOptions += `<option value="${t.id}">${window.escapeHTML(t.name)}</option>`;
    });

    body.innerHTML = `
        <div style="display:flex; flex-direction:column; gap:1.25rem; height:100%; width:100%;">
            <!-- Two Column Layout: Left Card Selector | Right Configurations -->
            <div style="display:flex; gap:1.5rem; flex:1; overflow-y:auto; min-height:0; padding-right:0.25rem;">
                
                <!-- Left: Export Type Cards Selection -->
                <div style="width:40%; display:flex; flex-direction:column; gap:0.75rem;">
                    <label class="form-label" style="font-weight:800; color:#475569; font-size:0.8rem; text-transform:uppercase; letter-spacing:0.05em;">
                        1. Select Export Type *
                    </label>

                    <div class="export-card active" data-type="Green Room Sign" style="border:2px solid #4338ca; background:#f5f3ff; border-radius:12px; padding:1rem; cursor:pointer; display:flex; align-items:center; gap:0.75rem; transition:all 0.2s;">
                        <span style="font-size:2rem; background:#fff; border-radius:8px; padding:0.4rem; border:1px solid #ddd;">🚪</span>
                        <div style="display:flex; flex-direction:column; gap:0.15rem;">
                            <strong style="color:#1e1b4b; font-size:0.92rem;">Green Room Sign</strong>
                            <span style="font-size:0.72rem; color:#64748b; font-weight:600;">Attendance checklist & signatures</span>
                        </div>
                    </div>

                    <div class="export-card" data-type="Valuation Sheet" style="border:2px solid #e2e8f0; background:#fff; border-radius:12px; padding:1rem; cursor:pointer; display:flex; align-items:center; gap:0.75rem; transition:all 0.2s;">
                        <span style="font-size:2rem; background:#fff; border-radius:8px; padding:0.4rem; border:1px solid #ddd;">📝</span>
                        <div style="display:flex; flex-direction:column; gap:0.15rem;">
                            <strong style="color:#1e1b4b; font-size:0.92rem;">Valuation Sheet</strong>
                            <span style="font-size:0.72rem; color:#64748b; font-weight:600;">Blank markings layout for judges</span>
                        </div>
                    </div>

                    <div class="export-card" data-type="Call List" style="border:2px solid #e2e8f0; background:#fff; border-radius:12px; padding:1rem; cursor:pointer; display:flex; align-items:center; gap:0.75rem; transition:all 0.2s;">
                        <span style="font-size:2rem; background:#fff; border-radius:8px; padding:0.4rem; border:1px solid #ddd;">📣</span>
                        <div style="display:flex; flex-direction:column; gap:0.15rem;">
                            <strong style="color:#1e1b4b; font-size:0.92rem;">Call List</strong>
                            <span style="font-size:0.72rem; color:#64748b; font-weight:600;">Stage calling roster checklist</span>
                        </div>
                    </div>

                    <div class="export-card" data-type="Results" style="border:2px solid #e2e8f0; background:#fff; border-radius:12px; padding:1rem; cursor:pointer; display:flex; align-items:center; gap:0.75rem; transition:all 0.2s;">
                        <span style="font-size:2rem; background:#fff; border-radius:8px; padding:0.4rem; border:1px solid #ddd;">🏆</span>
                        <div style="display:flex; flex-direction:column; gap:0.15rem;">
                            <strong style="color:#1e1b4b; font-size:0.92rem;">Results Reports</strong>
                            <span style="font-size:0.72rem; color:#64748b; font-weight:600;">Team, Program or Student distribution</span>
                        </div>
                    </div>
                </div>

                <!-- Right: Configuration Parameters -->
                <div style="flex:1; border:1px solid #cbd5e1; border-radius:12px; background:#f8fafc; padding:1.25rem; display:flex; flex-direction:column; gap:1rem;">
                    <label class="form-label" style="font-weight:800; color:#475569; font-size:0.8rem; text-transform:uppercase; letter-spacing:0.05em; border-bottom:1px solid #cbd5e1; padding-bottom:0.4rem;">
                        2. Configuration Filters & Formats
                    </label>

                    <!-- Sub Options (Only visible for Results) -->
                    <div id="expResultSub" style="display:none; flex-direction:column; gap:0.45rem;">
                        <label class="form-label" style="font-weight:700; color:#475569;">RESULTS SUB-OPTION *</label>
                        <select id="expResultSubVal" class="form-input" style="background:#fff;">
                            <option value="Team Wise">Team Wise Results</option>
                            <option value="Program Wise">Program Wise Results</option>
                            <option value="Student Prize Distribution">Student Prize Distribution</option>
                        </select>
                    </div>

                    <!-- Category / Class Filter -->
                    <div style="display:flex; gap:0.75rem; flex-wrap:wrap;">
                        <div style="flex:1; min-width:180px;">
                            <label class="form-label" style="font-weight:700; color:#475569;">CATEGORY</label>
                            <select id="expCatFilter" class="form-input" style="background:#fff;">${catOptions}</select>
                        </div>
                        <div style="flex:1; min-width:180px;">
                            <label class="form-label" style="font-weight:700; color:#475569;">CLASS</label>
                            <select id="expClassFilter" class="form-input" style="background:#fff;" disabled>
                                <option value="">All Classes</option>
                            </select>
                        </div>
                    </div>

                    <!-- Program Filter -->
                    <div>
                        <label class="form-label" style="font-weight:700; color:#475569;">SPECIFIC PROGRAM (OPTIONAL)</label>
                        <select id="expProgFilter" class="form-input" style="background:#fff;">
                            <option value="">All Matching Programs</option>
                        </select>
                    </div>

                    <!-- Gender & Team Filter -->
                    <div style="display:flex; gap:0.75rem; flex-wrap:wrap;">
                        <div style="flex:1; min-width:180px;">
                            <label class="form-label" style="font-weight:700; color:#475569;">GENDER</label>
                            <select id="expGenderFilter" class="form-input" style="background:#fff;">
                                <option value="">All Genders</option>
                                <option value="Boys">Boys</option>
                                <option value="Girls">Girls</option>
                                <option value="Mixed">Mixed</option>
                            </select>
                        </div>
                        <div style="flex:1; min-width:180px;">
                            <label class="form-label" style="font-weight:700; color:#475569;">TEAM</label>
                            <select id="expTeamFilter" class="form-input" style="background:#fff;">${teamOptions}</select>
                        </div>
                    </div>

                    <!-- Result Export Source (Only visible for Results) -->
                    <div id="resultsSourceContainer" style="display:none; flex-direction:column; gap:0.45rem; background:#fff; border:1px solid #cbd5e1; padding:0.75rem 1rem; border-radius:10px;">
                        <span style="font-size:0.78rem; font-weight:700; color:#475569; display:block; margin-bottom:0.25rem;">RESULT SOURCE FILTERS</span>
                        <div style="display:flex; gap:1.25rem;">
                            <label style="display:inline-flex; align-items:center; gap:0.4rem; font-size:0.8rem; font-weight:600; color:#475569; cursor:pointer; user-select:none;">
                                <input type="checkbox" id="srcIncludeSubmitted" style="cursor:pointer;" /> Include Submitted
                            </label>
                            <label style="display:inline-flex; align-items:center; gap:0.4rem; font-size:0.8rem; font-weight:600; color:#475569; cursor:pointer; user-select:none;">
                                <input type="checkbox" id="srcIncludeDraft" style="cursor:pointer;" /> Include Draft
                            </label>
                        </div>
                        <span style="font-size:0.68rem; color:#64748b; display:block; margin-top:0.2rem;">By default, only dynamic <strong>Published</strong> results are generated.</span>
                    </div>

                    <!-- PDF Orientation & Download Format -->
                    <div style="display:flex; gap:0.75rem; flex-wrap:wrap; border-top:1px solid #cbd5e1; padding-top:0.75rem; margin-top:0.25rem;">
                        <div style="flex:1; min-width:180px;">
                            <label class="form-label" style="font-weight:700; color:#475569;">DOCUMENT LAYOUT / ORIENTATION</label>
                            <select id="expOrientation" class="form-input" style="background:#fff;">
                                <option value="portrait">A4 Portrait</option>
                                <option value="landscape">A4 Landscape</option>
                            </select>
                        </div>
                        <div style="flex:1; min-width:180px;">
                            <label class="form-label" style="font-weight:700; color:#475569;">DOWNLOAD FORMAT</label>
                            <select id="expFormat" class="form-input" style="background:#fff;">
                                <option value="pdf">PDF (Printable Tab)</option>
                                <option value="csv">CSV Spreadsheet</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Footer Buttons -->
            <div class="modal-actions" style="margin-top:0.25rem; border-top:1px solid #cbd5e1; padding-top:0.75rem; display:flex;">
                <button type="button" class="btn btn-secondary" id="btnNewExpCancel">Cancel</button>
                <button type="button" class="btn btn-primary" id="btnNewExpGenerate" style="margin-left:auto; font-weight:700; min-width:160px;">
                    ⚡ Generate Export
                </button>
            </div>
        </div>
    `;

    // Dynamic Select Variables
    let selectedType = 'Green Room Sign';
    const cards = body.querySelectorAll('.export-card');
    const resultsSourceContainer = document.getElementById('resultsSourceContainer');
    const subOptionsContainer = document.getElementById('expResultSub');
    const expCatFilter = document.getElementById('expCatFilter');
    const expClassFilter = document.getElementById('expClassFilter');
    const expProgFilter = document.getElementById('expProgFilter');

    // Setup active selector cards
    cards.forEach(card => {
        card.onclick = () => {
            cards.forEach(c => {
                c.style.border = '2px solid #e2e8f0';
                c.style.background = '#fff';
                c.classList.remove('active');
            });
            card.style.border = '2px solid #4338ca';
            card.style.background = '#f5f3ff';
            card.classList.add('active');

            selectedType = card.getAttribute('data-type');

            if (selectedType === 'Results') {
                resultsSourceContainer.style.display = 'flex';
                subOptionsContainer.style.display = 'flex';
            } else {
                resultsSourceContainer.style.display = 'none';
                subOptionsContainer.style.display = 'none';
            }
        };
    });

    // Populate class dynamically based on category
    expCatFilter.onchange = async () => {
        const catId = expCatFilter.value;
        expClassFilter.innerHTML = '<option value="">All Classes</option>';
        expClassFilter.disabled = true;

        if (catId) {
            const cat = allCategories.find(c => c.id === catId);
            if (cat && cat.classes) {
                cat.classes.forEach(c => {
                    expClassFilter.innerHTML += `<option value="${c.id}">${window.escapeHTML(c.name)}</option>`;
                });
                expClassFilter.disabled = false;
            }
        }
        updateProgramsDropdown();
    };

    expClassFilter.onchange = () => updateProgramsDropdown();

    function updateProgramsDropdown() {
        const catId = expCatFilter.value;
        const classId = expClassFilter.value;

        expProgFilter.innerHTML = '<option value="">All Matching Programs</option>';
        
        const filtered = allPrograms.filter(p => {
            if (catId && p.categoryId !== catId) return false;
            if (classId && p.classId !== classId) return false;
            return true;
        });

        filtered.forEach(p => {
            expProgFilter.innerHTML += `<option value="${p.id}">${window.escapeHTML(p.programName)}</option>`;
        });
    }

    // Run first program loading
    updateProgramsDropdown();

    // Bind footer actions
    document.getElementById('btnNewExpCancel').onclick = closeExportDrawer;

    document.getElementById('btnNewExpGenerate').onclick = async () => {
        const btn = document.getElementById('btnNewExpGenerate');
        btn.disabled = true;
        btn.textContent = 'Queuing Export...';

        const categoryId = expCatFilter.value;
        const categoryName = categoryId ? allCategories.find(c => c.id === categoryId)?.name : 'All';
        const classId = expClassFilter.value;
        const className = classId ? allCategories.find(c => c.id === categoryId)?.classes.find(cls => cls.id === classId)?.name : '';
        const programId = expProgFilter.value;
        const programName = programId ? allPrograms.find(p => p.id === programId)?.programName : 'All';
        const gender = document.getElementById('expGenderFilter').value;
        const teamId = document.getElementById('expTeamFilter').value;
        const teamName = teamId ? allTeams.find(t => t.id === teamId)?.name : 'All';

        const resultSubOption = selectedType === 'Results' ? document.getElementById('expResultSubVal').value : 'Team Wise';
        const format = document.getElementById('expFormat').value;
        const orientation = document.getElementById('expOrientation').value;
        const srcIncludeSubmitted = document.getElementById('srcIncludeSubmitted').checked;
        const srcIncludeDraft = document.getElementById('srcIncludeDraft').checked;

        // Form unique filename
        const cleanName = (str) => str.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
        const dateStr = new Date().toISOString().split('T')[0];
        
        let fileTypePrefix = cleanName(selectedType);
        if (selectedType === 'Results') {
            fileTypePrefix = cleanName(resultSubOption);
        }

        let scopeText = '';
        if (programId) scopeText = `_${cleanName(programName)}`;
        else if (categoryId) scopeText = `_${cleanName(categoryName)}`;
        
        const finalFilename = `${fileTypePrefix}${scopeText}_${dateStr}.${format}`;

        // Create Queued Export Document in Firestore
        try {
            const instId = window.currentInstituteId;
            const ref = collection(db, "institutes", instId, "exports");
            
            const payload = {
                type: selectedType,
                fileName: finalFilename,
                summary: `Scope: ${categoryName}${className ? ` (${className})` : ''} | Program: ${programName} | Team: ${teamName} [${format.toUpperCase()}]`,
                status: 'Pending',
                queuedAt: serverTimestamp(),
                completedIn: '—',
                generatedBy: window.currentInstituteDetails?.name || 'Admin',
                filters: {
                    type: selectedType,
                    resultSubOption,
                    categoryId,
                    classId,
                    programId,
                    gender,
                    teamId,
                    format,
                    orientation,
                    srcIncludeSubmitted,
                    srcIncludeDraft
                }
            };

            const docRef = await addDoc(ref, payload);
            closeExportDrawer();

            // Run standard Status Workflow simulation pipelines
            simulateExportProcessing(docRef.id);

        } catch (err) {
            console.error("Generate error:", err);
            window.showToast("Failed to queue export document.", "error");
            btn.disabled = false;
            btn.textContent = '⚡ Generate Export';
        }
    };
}

// ─────────────────────────────────────────────
// Queuing Status Simulation Pipeline
// ─────────────────────────────────────────────
async function simulateExportProcessing(docId) {
    const instId = window.currentInstituteId;
    const docRef = doc(db, "institutes", instId, "exports", docId);

    // Transitions from Pending ➔ Processing after 400ms
    setTimeout(async () => {
        try {
            await updateDoc(docRef, { status: 'Processing' });

            // Transitions to Completed after 900ms
            setTimeout(async () => {
                try {
                    const elapsed = (Math.random() * 0.6 + 0.6).toFixed(1);
                    await updateDoc(docRef, {
                        status: 'Completed',
                        completedIn: `${elapsed}s`
                    });
                    window.showToast("⚡ Export document generated successfully!", "success");
                } catch (e) {
                    await updateDoc(docRef, { status: 'Failed' });
                }
            }, 900);

        } catch (e) {
            await updateDoc(docRef, { status: 'Failed' });
        }
    }, 400);
}

// ─────────────────────────────────────────────
// Retry Handler for Failed Items
// ─────────────────────────────────────────────
async function triggerRetry(exp) {
    const instId = window.currentInstituteId;
    const docRef = doc(db, "institutes", instId, "exports", exp.id);
    
    try {
        await updateDoc(docRef, {
            status: 'Pending',
            completedIn: '—',
            queuedAt: serverTimestamp()
        });
        window.showToast("🔄 Retrying export generation...", "info");
        simulateExportProcessing(exp.id);
    } catch (e) {
        console.error(e);
    }
}

// ─────────────────────────────────────────────
// Deletion Safety Trigger (Log history only!)
// ─────────────────────────────────────────────
async function triggerDelete(exp) {
    if (!confirm("Are you sure you want to delete this export history log?\n(This will not affect any students, results, or program records).")) return;

    try {
        const instId = window.currentInstituteId;
        await deleteDoc(doc(db, "institutes", instId, "exports", exp.id));
        window.showToast("History log removed successfully.", "success");
    } catch (e) {
        console.error(e);
        window.showToast("Failed to delete log.", "error");
    }
}

// ─────────────────────────────────────────────
// Dynamic Compilation & Download Router
// ─────────────────────────────────────────────
async function triggerDownload(exp) {
    window.showToast(`Loading data for ${exp.fileName}...`, "info");
    const instId = window.currentInstituteId;

    try {
        const f = exp.filters;
        if (!f) throw new Error("Filters parameters are missing.");

        // 1. Fetch matching programs list
        let programs = [...allPrograms];
        if (f.programId) {
            programs = allPrograms.filter(p => p.id === f.programId);
        } else {
            programs = allPrograms.filter(p => {
                if (f.categoryId && p.categoryId !== f.categoryId) return false;
                if (f.classId && p.classId !== f.classId) return false;
                if (f.gender && p.genderCategory !== f.gender) return false;
                return true;
            });
        }

        if (programs.length === 0 && f.type !== 'Results') {
            window.showToast("No programs match the selected filters.", "warning");
            return;
        }

        // 2. Fetch Results list
        const resultsSnap = await getDocs(collection(db, "institutes", instId, "results"));
        const resultsList = resultsSnap.docs.map(d => ({ id: d.id, ...d.data() }));

        // 3. Compile and trigger
        if (f.format === 'csv') {
            compileCSV(exp, f, programs, resultsList);
        } else {
            compilePDF(exp, f, programs, resultsList);
        }

    } catch (err) {
        console.error("Compilation error:", err);
        window.showToast(`Unable to download: ${err.message || err}`, "error");
    }
}

// ─────────────────────────────────────────────
// PDF Printable High-Fidelity Tab Compiler
// ─────────────────────────────────────────────
async function compilePDF(exp, f, programs, resultsList) {
    let htmlContent = '';
    const instId = window.currentInstituteId;
    const orientation = f.orientation || 'portrait';

    if (f.type === 'Green Room Sign') {
        for (let i = 0; i < programs.length; i++) {
            const p = programs[i];
            const parts = await loadParticipants(p, f.teamId);
            
            htmlContent += `
                <div class="program-page">
                    <div class="report-header">
                        <div>
                            <div class="report-title">🚪 GREEN ROOM SIGN-IN</div>
                            <h2 style="margin-top:0.4rem;">${window.escapeHTML(p.programName)}</h2>
                            <div style="font-size:0.8rem; font-weight:600; color:#4338ca; margin-top:0.2rem;">
                                Category: ${window.escapeHTML(p.categoryName)} ${p.className ? `(${window.escapeHTML(p.className)})` : ''} · 
                                Type: ${p.programType === 'group' ? 'Group' : 'Individual'}
                            </div>
                        </div>
                        <div style="text-align:right;">
                            <span style="font-size:0.75rem; font-weight:700; color:#64748b; text-transform:uppercase; display:block;">Total Entries</span>
                            <span style="font-weight:800; font-size:1.4rem; color:#1e1b4b;">${parts.length} Participants</span>
                        </div>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style="width:60px; text-align:center;">SL No</th>
                                <th style="width:110px; text-align:center;">Chest No</th>
                                <th>Participant / Team Name</th>
                                <th style="width:120px; text-align:center;">Code Letter</th>
                                <th style="width:220px; text-align:center;">Signature</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${parts.length === 0 ? `<tr><td colspan="5" style="text-align:center; padding:2rem; color:#64748b;">No registered participants.</td></tr>` : 
                              parts.map((item, idx) => `
                                <tr style="height:38px;">
                                    <td style="text-align:center; font-weight:700; color:#475569;">${idx + 1}</td>
                                    <td style="text-align:center; font-weight:800; color:#0f172a;">${window.escapeHTML(item.chestNumber || '—')}</td>
                                    <td style="font-weight:700; color:#1e293b;">${window.escapeHTML(item.name)}</td>
                                    <td style="text-align:center;"></td>
                                    <td></td>
                                </tr>
                              `).join('')}
                        </tbody>
                    </table>
                </div>
            `;
        }
    }

    else if (f.type === 'Valuation Sheet') {
        for (let i = 0; i < programs.length; i++) {
            const p = programs[i];
            const parts = await loadParticipants(p, f.teamId);
            
            htmlContent += `
                <div class="program-page">
                    <div class="report-header">
                        <div>
                            <div class="report-title">📝 JUDGE VALUATION SHEET</div>
                            <h2 style="margin-top:0.4rem;">${window.escapeHTML(p.programName)}</h2>
                            <div style="font-size:0.8rem; font-weight:600; color:#4338ca; margin-top:0.2rem;">
                                Category: ${window.escapeHTML(p.categoryName)} ${p.className ? `(${window.escapeHTML(p.className)})` : ''} · 
                                Type: ${p.programType === 'group' ? 'Group' : 'Individual'}
                            </div>
                        </div>
                        <div style="text-align:right;">
                            <span style="font-size:0.75rem; font-weight:700; color:#64748b; text-transform:uppercase; display:block;">Evaluation Sheet</span>
                            <span style="font-weight:800; font-size:1.1rem; color:#1e1b4b; display:block; margin-top:0.2rem; border-bottom:1px solid #94a3b8; width:220px; text-align:left;">Judge Name: </span>
                        </div>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style="width:70px; text-align:center;">SL No</th>
                                <th style="width:160px; text-align:center;">Code Letter</th>
                                <th style="width:200px; text-align:center;">Mark / Score (0-100)</th>
                                <th style="text-align:center;">Total Mark Notes / Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${parts.length === 0 ? `<tr><td colspan="4" style="text-align:center; padding:2rem; color:#64748b;">No registered entries.</td></tr>` : 
                              parts.map((item, idx) => `
                                <tr style="height:40px;">
                                    <td style="text-align:center; font-weight:700; color:#475569;">${idx + 1}</td>
                                    <td style="text-align:center; font-weight:800; color:#0f172a;"></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                              `).join('')}
                        </tbody>
                    </table>
                </div>
            `;
        }
    }

    else if (f.type === 'Call List') {
        for (let i = 0; i < programs.length; i++) {
            const p = programs[i];
            const parts = await loadParticipants(p, f.teamId);
            
            htmlContent += `
                <div class="program-page">
                    <div class="report-header">
                        <div>
                            <div class="report-title">📣 OFFICIAL STAGE CALL LIST</div>
                            <h2 style="margin-top:0.4rem;">${window.escapeHTML(p.programName)}</h2>
                            <div style="font-size:0.8rem; font-weight:600; color:#4338ca; margin-top:0.2rem;">
                                Category: ${window.escapeHTML(p.categoryName)} ${p.className ? `(${window.escapeHTML(p.className)})` : ''} · 
                                Type: ${p.programType === 'group' ? 'Group' : 'Individual'}
                            </div>
                        </div>
                        <div style="text-align:right;">
                            <span style="font-size:0.75rem; font-weight:700; color:#64748b; text-transform:uppercase; display:block;">Call List</span>
                            <span style="font-weight:800; font-size:1.4rem; color:#1e1b4b;">${parts.length} Participants</span>
                        </div>
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style="width:70px; text-align:center;">SL No</th>
                                <th style="width:140px; text-align:center;">Chest No</th>
                                <th>Participant Name</th>
                                <th>Team / Institute Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${parts.length === 0 ? `<tr><td colspan="4" style="text-align:center; padding:2rem; color:#64748b;">No registered participants.</td></tr>` : 
                              parts.map((item, idx) => `
                                <tr>
                                    <td style="text-align:center; font-weight:700; color:#475569;">${idx + 1}</td>
                                    <td style="text-align:center; font-weight:800; color:#0f172a;">${window.escapeHTML(item.chestNumber || '—')}</td>
                                    <td style="font-weight:700; color:#1e293b;">${window.escapeHTML(item.name)}</td>
                                    <td style="font-weight:600; color:#475569;">${window.escapeHTML(item.teamName || 'Group Entry')}</td>
                                </tr>
                              `).join('')}
                        </tbody>
                    </table>
                </div>
            `;
        }
    }

    else if (f.type === 'Results') {
        const filteredResults = filterResultsBySource(resultsList, f);

        if (filteredResults.length === 0) {
            htmlContent = `
                <div style="text-align:center; padding:4rem; color:#ef4444;">
                    <h3>⚠️ No published result records found.</h3>
                    <p style="color:#64748b;">Double check source selectors and filters configurations.</p>
                </div>
            `;
        }

        else if (f.resultSubOption === 'Team Wise') {
            // Group winners by Team
            const teamWinners = new Map();
            filteredResults.forEach(r => {
                const winners = Array.isArray(r.winners) ? r.winners : [];
                winners.forEach(w => {
                    if (!w.teamName) return;
                    if (f.teamId && w.teamId !== f.teamId) return;

                    if (!teamWinners.has(w.teamName)) {
                        teamWinners.set(w.teamName, { First: [], Second: [], Third: [] });
                    }
                    const entry = {
                        programName: r.programName,
                        categoryName: r.categoryName,
                        studentName: w.studentName,
                        chestNumber: w.chestNumber || '—'
                    };

                    if (w.position === 'First') teamWinners.get(w.teamName).First.push(entry);
                    else if (w.position === 'Second') teamWinners.get(w.teamName).Second.push(entry);
                    else if (w.position === 'Third') teamWinners.get(w.teamName).Third.push(entry);
                });
            });

            if (teamWinners.size === 0) {
                htmlContent = `<div style="text-align:center; padding:3rem; color:#64748b;">No matching team placements recorded yet.</div>`;
            } else {
                const sortedTeamNames = [...teamWinners.keys()].sort();
                sortedTeamNames.forEach(teamName => {
                    const data = teamWinners.get(teamName);
                    
                    const renderRows = (list, posLabel) => {
                        if (list.length === 0) return `<tr><td colspan="4" style="color:#94a3b8; font-style:italic;">No ${posLabel} place winners.</td></tr>`;
                        return list.map(item => `
                            <tr>
                                <td style="font-weight:700; color:#1e293b;">${window.escapeHTML(item.programName)}</td>
                                <td style="color:#475569;">${window.escapeHTML(item.categoryName)}</td>
                                <td style="text-align:center; font-weight:800;">${window.escapeHTML(item.chestNumber)}</td>
                                <td style="font-weight:700; color:#4338ca;">${window.escapeHTML(item.studentName)}</td>
                            </tr>
                        `).join('');
                    };

                    htmlContent += `
                        <div class="program-page" style="border:1px solid #cbd5e1; border-radius:12px; padding:1.25rem; margin-bottom:1.5rem; background:#fff;">
                            <div style="border-bottom:2px solid #1e1b4b; padding-bottom:0.5rem; margin-bottom:1rem;">
                                <h2 style="color:#1e1b4b;">👥 TEAM STANDINGS: ${window.escapeHTML(teamName)}</h2>
                            </div>

                            <h4 style="color:#d97706; margin-top:0.75rem; margin-bottom:0.4rem;">🥇 FIRST WINNERS</h4>
                            <table style="margin-bottom:1rem;">
                                <thead>
                                    <tr style="background:#fffbeb;">
                                        <th>Program</th>
                                        <th>Category</th>
                                        <th style="width:100px; text-align:center;">Chest No</th>
                                        <th>Winner Name</th>
                                    </tr>
                                </thead>
                                <tbody>${renderRows(data.First, 'first')}</tbody>
                            </table>

                            <h4 style="color:#475569; margin-top:1.25rem; margin-bottom:0.4rem;">🥈 SECOND WINNERS</h4>
                            <table style="margin-bottom:1rem;">
                                <thead>
                                    <tr style="background:#f8fafc;">
                                        <th>Program</th>
                                        <th>Category</th>
                                        <th style="width:100px; text-align:center;">Chest No</th>
                                        <th>Winner Name</th>
                                    </tr>
                                </thead>
                                <tbody>${renderRows(data.Second, 'second')}</tbody>
                            </table>

                            <h4 style="color:#ea580c; margin-top:1.25rem; margin-bottom:0.4rem;">🥉 THIRD WINNERS</h4>
                            <table>
                                <thead>
                                    <tr style="background:#fff7ed;">
                                        <th>Program</th>
                                        <th>Category</th>
                                        <th style="width:100px; text-align:center;">Chest No</th>
                                        <th>Winner Name</th>
                                    </tr>
                                </thead>
                                <tbody>${renderRows(data.Third, 'third')}</tbody>
                            </table>
                        </div>
                    `;
                });
            }
        }

        else if (f.resultSubOption === 'Program Wise') {
            filteredResults.forEach(r => {
                const winnersList = Array.isArray(r.winners) ? r.winners : [];
                
                // Sort by position order
                const posOrder = { 'First': 1, 'Second': 2, 'Third': 3 };
                const sortedWinners = [...winnersList].sort((a, b) => (posOrder[a.position] || 4) - (posOrder[b.position] || 4));

                htmlContent += `
                    <div class="program-page" style="border:1px solid #cbd5e1; border-radius:12px; padding:1.25rem; margin-bottom:1.5rem; background:#fff;">
                        <div class="report-header">
                            <div>
                                <div class="report-title">🏆 PROGRAM RESULTS PODIUM</div>
                                <h2 style="margin-top:0.4rem;">${window.escapeHTML(r.programName)}</h2>
                                <div style="font-size:0.8rem; font-weight:600; color:#4338ca; margin-top:0.2rem;">
                                    Category: ${window.escapeHTML(r.categoryName)} ${r.className ? `(${window.escapeHTML(r.className)})` : ''} · 
                                    Type: ${r.programType === 'group' ? 'Group' : 'Individual'}
                                </div>
                            </div>
                            <div style="text-align:right;">
                                <span style="font-size:0.75rem; font-weight:700; color:#64748b; text-transform:uppercase; display:block;">Stage / Room</span>
                                <span style="font-weight:800; font-size:1rem; color:#1e1b4b;">${window.escapeHTML(r.programLocation || 'Stage')}</span>
                            </div>
                        </div>

                        <table>
                            <thead>
                                <tr>
                                    <th style="width:110px; text-align:center;">Position</th>
                                    <th style="width:110px; text-align:center;">Chest No</th>
                                    <th>Name</th>
                                    <th>Team / Institute Name</th>
                                    <th style="width:90px; text-align:center;">Grade</th>
                                    <th style="width:100px; text-align:center;">Points</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${sortedWinners.length === 0 ? `<tr><td colspan="6" style="text-align:center; padding:2rem; color:#64748b;">No winners recorded for this program.</td></tr>` : 
                                  sortedWinners.map(w => {
                                    let posBadge = '';
                                    if (w.position === 'First') posBadge = '🥇 First';
                                    else if (w.position === 'Second') posBadge = '🥈 Second';
                                    else if (w.position === 'Third') posBadge = '🥉 Third';
                                    else posBadge = w.position;

                                    let grade = w.grade || '—';
                                    let points = w.marks !== undefined ? `${w.marks}pts` : '0pts';

                                    // Try loading extra details from marksData
                                    if (Array.isArray(r.marksData)) {
                                        const match = r.marksData.find(m => 
                                            (r.programType === 'group' && m.teamName === w.teamName) || 
                                            (r.programType !== 'group' && m.studentId === w.studentId) || 
                                            (r.programType !== 'group' && m.studentName === w.studentName)
                                        );
                                        if (match) {
                                            grade = match.grade || grade;
                                            points = match.totalPoints !== undefined ? `${match.totalPoints}pts` : points;
                                        }
                                    }

                                    return `
                                        <tr>
                                            <td style="text-align:center; font-weight:800; color:#1e1b4b;">${posBadge}</td>
                                            <td style="text-align:center; font-weight:800; color:#0f172a;">${window.escapeHTML(w.chestNumber || '—')}</td>
                                            <td style="font-weight:700; color:#1e293b;">${window.escapeHTML(r.programType === 'group' ? w.teamName : w.studentName)}</td>
                                            <td style="font-weight:600; color:#475569;">${window.escapeHTML(w.teamName || '—')}</td>
                                            <td style="text-align:center; font-weight:700; color:#4338ca;">${grade}</td>
                                            <td style="text-align:center; font-weight:800; color:#16a34a;">${points}</td>
                                        </tr>
                                    `;
                                  }).join('')}
                            </tbody>
                        </table>
                    </div>
                `;
            });
        }

        else if (f.resultSubOption === 'Student Prize Distribution') {
            // Aggregate all student prizes into one combined student record
            const studentPrizes = new Map();

            filteredResults.forEach(r => {
                const winnersList = Array.isArray(r.winners) ? r.winners : [];
                winnersList.forEach(w => {
                    if (r.programType === 'group') return; // Students only
                    const stuKey = w.chestNumber || w.studentName;
                    if (!stuKey) return;

                    if (!studentPrizes.has(stuKey)) {
                        studentPrizes.set(stuKey, {
                            studentName: w.studentName,
                            chestNumber: w.chestNumber || '—',
                            teamName: w.teamName || '—',
                            prizes: []
                        });
                    }

                    studentPrizes.get(stuKey).prizes.push({
                        programName: r.programName,
                        position: w.position
                    });
                });
            });

            if (studentPrizes.size === 0) {
                htmlContent = `<div style="text-align:center; padding:3rem; color:#64748b;">No student prizes recorded under the selected parameters.</div>`;
            } else {
                const sortedStudents = [...studentPrizes.values()].sort((a, b) => a.studentName.localeCompare(b.studentName));
                
                htmlContent = `
                    <div style="border:1px solid #cbd5e1; border-radius:12px; padding:1.25rem; background:#fff; width:100%;">
                        <div style="border-bottom:2px solid #4338ca; padding-bottom:0.6rem; margin-bottom:1rem;">
                            <h2 style="color:#1e1b4b; margin:0;">🎖️ STUDENT PRIZE DISTRIBUTION REGISTER</h2>
                            <p style="margin:0.2rem 0 0 0; font-size:0.75rem; color:#64748b;">Aggregated student prizes list.</p>
                        </div>

                        <table>
                            <thead>
                                <tr>
                                    <th style="width:100px; text-align:center;">Chest No</th>
                                    <th>Student Name</th>
                                    <th>Team / Institute Name</th>
                                    <th>Prizes Summary & Placements</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${sortedStudents.map(stu => `
                                    <tr>
                                        <td style="text-align:center; font-weight:800; color:#0f172a;">${window.escapeHTML(stu.chestNumber)}</td>
                                        <td style="font-weight:800; color:#1e1b4b;">${window.escapeHTML(stu.studentName)}</td>
                                        <td style="font-weight:600; color:#475569;">${window.escapeHTML(stu.teamName)}</td>
                                        <td style="padding:0.4rem 0.75rem;">
                                            <div style="display:flex; flex-direction:column; gap:0.2rem;">
                                                ${stu.prizes.map(p => {
                                                    const icon = p.position === 'First' ? '🥇' : (p.position === 'Second' ? '🥈' : '🥉');
                                                    return `<span style="font-size:0.8rem; font-weight:700; color:#1e293b;">${icon} ${window.escapeHTML(p.programName)} ➔ <strong>${p.position}</strong></span>`;
                                                }).join('')}
                                            </div>
                                        </td>
                                    </tr>
                                `).join('')}
                            </tbody>
                        </table>
                    </div>
                `;
            }
        }
    }

    // Open a blank new tab, inject content, and print!
    const printTab = window.open('', '_blank');
    printTab.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>${window.escapeHTML(exp.fileName)}</title>
            <style>
                @page {
                    size: A4 ${orientation};
                    margin: 15mm;
                }
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                    color: #1e293b;
                    margin: 0;
                    padding: 0;
                    background: #fff;
                    font-size: 0.85rem;
                }
                h2, h3, h4 {
                    margin: 0;
                    color: #1e1b4b;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 1rem;
                    font-size: 0.82rem;
                }
                th, td {
                    border: 1px solid #cbd5e1;
                    padding: 0.45rem 0.6rem;
                    text-align: left;
                    vertical-align: middle;
                }
                th {
                    background-color: #f8fafc !important;
                    color: #475569;
                    font-weight: 700;
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }
                tr {
                    page-break-inside: avoid;
                    break-inside: avoid;
                }
                thead {
                    display: table-header-group;
                }
                .program-page {
                    page-break-after: always;
                    break-after: page;
                }
                .program-page:last-child {
                    page-break-after: avoid;
                    break-after: avoid;
                }
                .report-header {
                    display: flex;
                    justify-content: space-between;
                    align-items: flex-start;
                    border-bottom: 2px solid #4338ca;
                    padding-bottom: 0.5rem;
                    margin-bottom: 1.25rem;
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }
                .report-title {
                    font-weight: 800;
                    font-size: 1.25rem;
                    color: #4338ca;
                    text-transform: uppercase;
                    letter-spacing: 0.05em;
                }
                .badge {
                    display: inline-block;
                    padding: 0.15rem 0.4rem;
                    border-radius: 4px;
                    font-size: 0.72rem;
                    font-weight: 700;
                    background: #e0e7ff;
                    color: #4338ca;
                    border: 1px solid #c7d2fe;
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }
            </style>
        </head>
        <body onload="window.print()">
            <div style="max-width:100%; margin: 0 auto;">
                ${htmlContent}
            </div>
        </body>
        </html>
    `);
    printTab.document.close();
}

// ─────────────────────────────────────────────
// CSV Dynamic Spreadsheet Blob Generator
// ─────────────────────────────────────────────
async function compileCSV(exp, f, programs, resultsList) {
    let csvContent = '';

    if (f.type === 'Green Room Sign') {
        csvContent += "PROGRAM,CATEGORY,TYPE,SL NO,CHEST NUMBER,PARTICIPANT NAME,CODE LETTER,SIGNATURE\n";
        
        for (let i = 0; i < programs.length; i++) {
            const p = programs[i];
            const parts = await loadParticipants(p, f.teamId);
            parts.forEach((item, idx) => {
                csvContent += `"${p.programName}","${p.categoryName}","${p.type}",${idx + 1},"${item.chestNumber || '—'}","${item.name}","",""\n`;
            });
        }
    }

    else if (f.type === 'Valuation Sheet') {
        csvContent += "PROGRAM,CATEGORY,TYPE,SL NO,CODE LETTER,MARK,TOTAL\n";
        
        for (let i = 0; i < programs.length; i++) {
            const p = programs[i];
            const parts = await loadParticipants(p, f.teamId);
            parts.forEach((item, idx) => {
                csvContent += `"${p.programName}","${p.categoryName}","${p.type}",${idx + 1},"","",""\n`;
            });
        }
    }

    else if (f.type === 'Call List') {
        csvContent += "PROGRAM,CATEGORY,TYPE,SL NO,CHEST NUMBER,PARTICIPANT NAME,TEAM NAME\n";
        
        for (let i = 0; i < programs.length; i++) {
            const p = programs[i];
            const parts = await loadParticipants(p, f.teamId);
            parts.forEach((item, idx) => {
                csvContent += `"${p.programName}","${p.categoryName}","${p.type}",${idx + 1},"${item.chestNumber || '—'}","${item.name}","${item.teamName || ''}"\n`;
            });
        }
    }

    else if (f.type === 'Results') {
        const filteredResults = filterResultsBySource(resultsList, f);

        if (f.resultSubOption === 'Team Wise') {
            csvContent += "TEAM NAME,PLACEMENT,PROGRAM,CATEGORY,CHEST NUMBER,WINNER NAME\n";

            const teamWinners = new Map();
            filteredResults.forEach(r => {
                const winners = Array.isArray(r.winners) ? r.winners : [];
                winners.forEach(w => {
                    if (!w.teamName) return;
                    if (f.teamId && w.teamId !== f.teamId) return;

                    if (!teamWinners.has(w.teamName)) {
                        teamWinners.set(w.teamName, []);
                    }
                    teamWinners.get(w.teamName).push({
                        position: w.position,
                        programName: r.programName,
                        categoryName: r.categoryName,
                        studentName: w.studentName,
                        chestNumber: w.chestNumber || '—'
                    });
                });
            });

            const sortedTeams = [...teamWinners.keys()].sort();
            sortedTeams.forEach(teamName => {
                const entries = teamWinners.get(teamName);
                entries.forEach(e => {
                    csvContent += `"${teamName}","${e.position}","${e.programName}","${e.categoryName}","${e.chestNumber}","${e.studentName}"\n`;
                });
            });
        }

        else if (f.resultSubOption === 'Program Wise') {
            csvContent += "PROGRAM NAME,CATEGORY,POSITION,CHEST NUMBER,NAME,TEAM NAME,GRADE,POINTS\n";

            filteredResults.forEach(r => {
                const winnersList = Array.isArray(r.winners) ? r.winners : [];
                winnersList.forEach(w => {
                    let grade = w.grade || '—';
                    let points = w.marks !== undefined ? w.marks : 0;

                    if (Array.isArray(r.marksData)) {
                        const match = r.marksData.find(m => 
                            (r.programType === 'group' && m.teamName === w.teamName) || 
                            (r.programType !== 'group' && m.studentId === w.studentId) || 
                            (r.programType !== 'group' && m.studentName === w.studentName)
                        );
                        if (match) {
                            grade = match.grade || grade;
                            points = match.totalPoints !== undefined ? match.totalPoints : points;
                        }
                    }

                    csvContent += `"${r.programName}","${r.categoryName}","${w.position}","${w.chestNumber || '—'}","${r.programType === 'group' ? w.teamName : w.studentName}","${w.teamName || ''}","${grade}",${points}\n`;
                });
            });
        }

        else if (f.resultSubOption === 'Student Prize Distribution') {
            csvContent += "CHEST NUMBER,STUDENT NAME,TEAM,PRIZES SUMMARY\n";

            const studentPrizes = new Map();
            filteredResults.forEach(r => {
                const winnersList = Array.isArray(r.winners) ? r.winners : [];
                winnersList.forEach(w => {
                    if (r.programType === 'group') return; // Students only
                    const stuKey = w.chestNumber || w.studentName;
                    if (!stuKey) return;

                    if (!studentPrizes.has(stuKey)) {
                        studentPrizes.set(stuKey, {
                            studentName: w.studentName,
                            chestNumber: w.chestNumber || '—',
                            teamName: w.teamName || '—',
                            prizes: []
                        });
                    }

                    studentPrizes.get(stuKey).prizes.push(`${r.programName} -> ${w.position}`);
                });
            });

            const sortedStudents = [...studentPrizes.values()].sort((a, b) => a.studentName.localeCompare(b.studentName));
            sortedStudents.forEach(stu => {
                csvContent += `"${stu.chestNumber}","${stu.studentName}","${stu.teamName}","${stu.prizes.join('; ')}"\n`;
            });
        }
    }

    // Trigger standard File Download Blob
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", exp.fileName);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

// ─────────────────────────────────────────────
// Sub-Collection Helper: Loads students dynamically
// ─────────────────────────────────────────────
async function loadParticipants(prog, limitTeamId) {
    const snap = await getDocs(collection(db, "institutes", window.currentInstituteId, "programs", prog.id, "participants"));
    const isGroup = prog.programType === 'group';
    const list = [];

    snap.docs.forEach(d => {
        const p = d.data();
        if (limitTeamId && p.teamId !== limitTeamId) return;

        if (isGroup) {
            const groups = Array.isArray(p.groups) ? p.groups : [];
            if (groups.length > 0) {
                groups.forEach(g => {
                    list.push({
                        name: g.name || p.teamName || 'Group',
                        chestNumber: '—',
                        teamName: p.teamName || ''
                    });
                });
            } else {
                list.push({
                    name: p.teamName || 'Team',
                    chestNumber: '—',
                    teamName: p.teamName || ''
                });
            }
        } else {
            list.push({
                name: p.studentName || '—',
                chestNumber: p.chestNumber || '—',
                teamName: p.teamName || ''
            });
        }
    });
    return list;
}

// ─────────────────────────────────────────────
// Filters Results based on published/draft config
// ─────────────────────────────────────────────
function filterResultsBySource(results, f) {
    return results.filter(r => {
        // Filter by Category
        if (f.categoryId && r.categoryId !== f.categoryId) return false;
        if (f.classId && r.classId !== f.classId) return false;
        
        // Filter by program
        if (f.programId && r.programId !== f.programId) return false;

        // Default results display controls
        const isDraft = r.status === 'draft';
        const isSubmitted = r.markEntryStatus === 'submitted';

        if (r.status === 'published') return true;
        if (f.srcIncludeSubmitted && isDraft && isSubmitted) return true;
        if (f.srcIncludeDraft && isDraft && !isSubmitted) return true;

        return false;
    });
}
